# Copyright 2025 Meta-Hybrid Mount Authors
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "notify"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyhow = "1.0.101"
serde_json = "1.0.149"
tgbot = "0.42.0"
tokio = { version = "1.49.0", features = ["full"] }
